language: c

os:
  - linux
  - osx

compiler:
  - gcc

addons:
  apt:
    packages:
      - libfuse2
      - libfuse-dev
      - fuse-utils

# https://github.com/travis-ci/travis-ci/issues/5377
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pkg-config ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install automake   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libtool    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install intltool   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gettext    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install osxfuse    ; fi

script:
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
